### PR TITLE
Export audit log command in cmfive.php

### PR DESCRIPTION
**Pull request by MaddyUnderStars**
https://crm.2pisoftware.com/task/edit/1704

- [x] Export audit log table through `cmfive.php cmfive export_audit`. Exports all logs older than config `audit.export_length_seconds`, default 30 days as json. Deletes exported audits from database.
- [ ] Cron job. Should likely be implemented using system crontab instead of php
- [ ] Sending exported audit logs to s3/dropbox/etc
- [ ] Audit archive viewer

### CODE REVIEW

**Comment by adam-buckley** [comment]
I'm concerned about storing potentially sensitive information straight to disk with no simple way to move it somewhere more secure... @careck should we be moving these exports to S3 if possible?

**Comment by adam-buckley** [comment]
@MaddyUnderStars I've found 2 issues, the first is that you can access the log from via a URL so we'll need either an nginx config change that restricts access to .log files or move it to S3. The other issue is the log output is not valid JSON but I think could be valid JSONP - we don't use JSONP though so it'll have to be changed to output valid JSON.

The export itself works great though so it's a great start so far!

**Comment by MaddyUnderStars** [comment]
I  went with a single json object per line, which would potentially make it easier to read if the file is very large (don't need to read the entire json obj/array to parse any single entry). This is a pretty easy fix of course. Also yes, without an nginx rule it will be accessible. I assume the storage folder is not accessible via nginx, so perhaps a new `audit` folder in there for exports?

**Comment by MaddyUnderStars** [comment]
I did put a task in the pr description for sending to s3 as it was mentioned in the original ticket

**Pull request closed without merging**
