### PR TITLE
Phpunit 10 and dev tools script

### PR DESCRIPTION
**Pull request by mattbell87**
### Phpunit 10

This seems to run OK if you keep the filename the same as the class name. So I've separated tests in to subdirectories instead and I've tested to see if they execute the same. It seems to work great, no warnings/errors.

Please review, happy to refactor if needed.

### Dev tools script

When I went to install phpunit 10 I noticed another problem. We have phpunit 8 defined in many other places.

Currently there are several test platforms. This is to provide a single source of truth for the test platform. I would like this to eventually be used locally, in CI and in codespaces. The idea is if any of these dev tool packages require an update, just change one of these files and it would propagate to all systems.

It's based on the CI in cmfive-core.

### Removal of codeception and selenium

As discussed with @DerekCrannaford we've decided to drop these from the develop branch as they are no longer used. @Dane-2pi heads up this will likely affect codespaces. I will get a PR ready.

## Test PHPUnit 10

To test PHPUnit 10, run `.codepipeline/docker/install_dev_tools.sh` then `docker compose exec webapp php cmfive.php tests unit all`.

## Documentation

The scripts are well commented. Cmfive documentation could be created for `.codepipeline/docker/install_dev_tools.sh` for devs without a codespace, perhaps when it's more widely used.

### CODE REVIEW

**Comment by mattbell87** [comment]
@DerekCrannaford Selenium and Codeception are removed as we discussed. Let me know if you're happy with that.

**Comment by DerekCrannaford** [comment]
> @DerekCrannaford Selenium and Codeception are removed as we discussed. Let me know if you're happy with that.

@adam-buckley = Inviting you to have a quick think about this.

I like where it is heading, and now boilerplate/core do not lean on Codecept tests for actions (or feature reviews) removing Composer build for Codecept & the Selenium container stands to majorly speedup build times for various environments.

!!! BUT !!! Is it safe to skip ahead, if this hits from DEV into MASTER, while other (custom) modules demand test support?

In use, eg: CRM & STAFF modules are not yet entirely mature to run on Playwright alone.
CRM = almost there / needs conformance on actions once tests are migrated.
STAFF = no ci actions and no Playwright yet.

**Comment by mattbell87** [comment]
Codespace patch: https://github.com/2pisoftware/codespace_dev_box/pull/42

**Review by adam-buckley — COMMENTED** [review]
This looks great, as per discussion with Derek I think we just need to rip the band-aid off and turf Codeception. I wanna give it a go locally first

**Comment by mattbell87** [comment]
Patch for core CI here https://github.com/2pisoftware/cmfive-core/pull/278

Boilerplate still has some Codeception embedded that we need to remove. Seems to be coming from cmfiveTests.php?
https://github.com/2pisoftware/cmfive-core/actions?query=workflow%3ACI+branch%3Afix%2Fci-dev-tools

**Comment by mattbell87** [comment]
[cmfiveTests.php](https://github.com/2pisoftware/cmfive-boilerplate/blob/feat/phpunit-10/cmfiveTests.php) needs to be "de-codeceptionised" before we merge. Needs a meeting.

**Review by DerekCrannaford — APPROVED** [review]

**Pull request merged**
